version: '3.8'


services:
  client:
    build: 
      context: ./src/client
      dockerfile: Dockerfile
    image: client
    tty: true
    container_name: client-container
    command: npm start
    volumes:
      - ./src/client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports: 
      - 3000:3000
    env_file: ./src/client/.env
    networks:
      - app-network

  # mongo:
  #   image: mongo:latest
  #   volumes:
  #     - data-volume:/data/db
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - app-network


  server:
    build: 
      context: ./src/server
      dockerfile: Dockerfile
    image: bookish-server
    container_name: server-container
    command: npm start
    volumes:
      - ./src/server/:/usr/app
      - /usr/app/node_modules
    ports:
      - 4000:4000
    # depends_on:
    #   - mongo
    env_file: ./src/server/config.env
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local